flashcard_project/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'), 
    path('flashcards/', include(('flashcards.urls', 'flashcards'), namespace = 'flashcards')),
]

flashcards/urls.py
# flashcards app urls conf
from django.urls import path,include
from django.conf.urls import url
from . import views # . means we are in the same directory (views is in same directory as urls)

urlpatterns = [ 
    path('', views.flashcards, name = 'flashcards'), 
    path('create/', views.create_card_set, name = 'create_card_set'), 
    path('create_card/(?P<card_set_id>[\d]+)', views.create_card, name = 'create_card'), 
    path('delete/(?P<card_set_id>[\d]+)', views.delete_card_set, name = 'delete_card_set'), 
    path('delete_card/(?P<card_id>[\d]+)', views.delete_card, name = 'delete_card'), 
    path('edit/(?P<card_set_id>[\d]+)', views.edit_card_set, name = 'edit_card_set'),
    path('edit_card/(?P<card_id>[\d]+)', views.edit_card, name = 'edit_card'), 
    path('view/(?P<card_set_id>[\d]+)', views.view_card_set, name = 'view_card_set'), 
    path('dictionary/', views.dictionary, name = 'dictionary'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/home.html
{% extends 'base.html' %}

{% block head %}
<title>FlipIt | Home</title>
<head>
<meta name='viewport' content='width=device-width, initial-scale=1'>
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>
{% endblock %}

{% block body%}
<div class="container">

    <!--The <i> tag is a smily face :)-->
    <h3>Welcome to FlipIt - Let's Learn <i class='far fa-grin' style='font-size:24px'>
    </i></h3>

        <a class="btn btn-link" href="https://www.ets.org/gre/" role="button" target="_blank">
        <h5><b>GRE Official Site</b></h5></a>
        <br>
        <a class="btn btn-link" href="{% url 'flashcards:flashcards' %}" role="button">
        <h5><b>Flashcards</b></h5></a>

</div>
{% endblock %}